# Generated by Django 3.1.3 on 2021-06-30 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0007_auto_20210630_0220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='lesson_id',
            new_name='lesson',
        ),
    ]
